// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingBlazorApp.Core;

namespace TrainingBlazorApp.Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211212092437_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrainingBlazorApp.Core.Entities.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommaOffset")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrimaryUnitConverter")
                        .HasColumnType("float");

                    b.Property<string>("Shortcut")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CommaOffset = 0,
                            Name = "metr",
                            PrimaryUnit = "m",
                            PrimaryUnitConverter = 1.0,
                            Shortcut = "m"
                        },
                        new
                        {
                            Id = 2L,
                            CommaOffset = 2,
                            Name = "centymetr",
                            PrimaryUnit = "cm",
                            PrimaryUnitConverter = 0.01,
                            Shortcut = "cm"
                        },
                        new
                        {
                            Id = 3L,
                            CommaOffset = 0,
                            Name = "sztuka",
                            PrimaryUnit = "szt",
                            PrimaryUnitConverter = 1.0,
                            Shortcut = "szt"
                        },
                        new
                        {
                            Id = 4L,
                            CommaOffset = 3,
                            Name = "milimetr",
                            PrimaryUnit = "m",
                            PrimaryUnitConverter = 0.001,
                            Shortcut = "mm"
                        },
                        new
                        {
                            Id = 5L,
                            CommaOffset = 0,
                            Name = "metr kwadratowy",
                            PrimaryUnit = "m2",
                            PrimaryUnitConverter = 1.0,
                            Shortcut = "m2"
                        },
                        new
                        {
                            Id = 6L,
                            CommaOffset = 4,
                            Name = "centymetr kwadratowy",
                            PrimaryUnit = "cm2",
                            PrimaryUnitConverter = 0.0001,
                            Shortcut = "cm2"
                        },
                        new
                        {
                            Id = 7L,
                            CommaOffset = 0,
                            Name = "kilogram",
                            PrimaryUnit = "kg",
                            PrimaryUnitConverter = 1.0,
                            Shortcut = "kg"
                        },
                        new
                        {
                            Id = 8L,
                            CommaOffset = 3,
                            Name = "gram",
                            PrimaryUnit = "g",
                            PrimaryUnitConverter = 0.001,
                            Shortcut = "g"
                        },
                        new
                        {
                            Id = 9L,
                            CommaOffset = 6,
                            Name = "milimetr kwadratowy",
                            PrimaryUnit = "m2",
                            PrimaryUnitConverter = 9.9999999999999995E-07,
                            Shortcut = "mm2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
